#!/usr/bin/env node
/**
 * Post-build fix: wrap dist/server/index.js so that CF Workers `env` (bindings)
 * are forwarded into the TanStack Start request middleware chain as
 * `requestOpts.context`. This is what `envInjectionMiddleware` in
 * src/start.ts reads via AsyncLocalStorage, so route handlers and server
 * functions can call `getEnv()` to read secrets/vars.
 *
 * Why this exists:
 *   - The default @tanstack/react-start/server-entry has a `fetch(request)`
 *     signature that does NOT pass `env` through. Route loaders + server
 *     fns would then read `env` as `undefined` and fail.
 *   - src/server-entry.ts is the *source* wrapper, but @cloudflare/vite-plugin
 *     bundles it down to a flat re-export in dist/server/index.js (the actual
 *     deploy target), losing the wrapper logic.
 *   - This script rewrites dist/server/index.js after the vite build, swapping
 *     the bare `export { a7 as default }` for a proper `fetch(request, env, ctx)`
 *     handler that calls `a7.fetch(request, { context: env }, ctx)`.
 *
 * Idempotent: safe to re-run; if the file is already wrapped, it leaves it alone.
 *
 * Usage: `node scripts/postbuild-fix.mjs` (called by `bun run build`)
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const INDEX_PATH = join(ROOT, "dist", "server", "index.js");

if (!existsSync(INDEX_PATH)) {
  console.error(`❌ postbuild-fix: ${INDEX_PATH} not found. Run 'bun run build' first.`);
  process.exit(1);
}

const original = readFileSync(INDEX_PATH, "utf8").trim();

// Already wrapped? Idempotent guard — detect by signature.
if (original.includes("innerEntry") && original.includes("context: env")) {
  console.log("✓ postbuild-fix: dist/server/index.js already wrapped, skipping.");
  process.exit(0);
}

// Extract the worker-entry asset path from the original re-export.
// Matches:  import { <any-symbol> } from "./assets/worker-entry-<hash>.js";
const workerImportMatch = original.match(
  /import\s*\{\s*([a-zA-Z_$][\w$]*)\s*\}\s*from\s*["']\.\/(assets\/worker-entry-[^"']+)["']\s*;?/,
);
const workerEntrySymbol = workerImportMatch?.[1];
if (!workerImportMatch) {
  console.error("❌ postbuild-fix: could not find worker-entry import in dist/server/index.js");
  console.error("   Original content:");
  console.error(
    original
      .split("\n")
      .map((l) => "   " + l)
      .join("\n"),
  );
  process.exit(1);
}
const workerAsset = workerImportMatch[2];

// Extract any `import "node:..."` polyfill lines, preserve them.
const polyfillImports = original
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => /^import\s+["']node:/.test(l));

const wrapped = [
  `// AUTO-GENERATED by scripts/postbuild-fix.mjs — do not edit by hand.`,
  `// Re-run \`bun run build\` to regenerate.`,
  ``,
  `import { ${workerEntrySymbol} as innerEntry } from "./${workerAsset}";`,
  ...polyfillImports,
  ``,
  `export default {`,
  `  async fetch(request, env, ctx) {`,
  `    // Pass env as requestOpts.context so TanStack Start's requestMiddleware`,
  `    // chain (including envInjectionMiddleware in src/start.ts) can read it.`,
  `    return innerEntry.fetch(request, { context: env }, ctx);`,
  `  },`,
  `};`,
  ``,
].join("\n");

writeFileSync(INDEX_PATH, wrapped, "utf8");
console.log(`✓ postbuild-fix: wrapped dist/server/index.js (worker=${workerAsset})`);
