/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutRouteImport } from './routes/_authenticated/workout'
import { Route as AuthenticatedWeightRouteImport } from './routes/_authenticated/weight'
import { Route as AuthenticatedWearableRouteImport } from './routes/_authenticated/wearable'
import { Route as AuthenticatedWaterRouteImport } from './routes/_authenticated/water'
import { Route as AuthenticatedVitalsRouteImport } from './routes/_authenticated/vitals'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedSleepRouteImport } from './routes/_authenticated/sleep'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedReverseCalorieRouteImport } from './routes/_authenticated/reverse-calorie'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedRecommendationsRouteImport } from './routes/_authenticated/recommendations'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrayerRouteImport } from './routes/_authenticated/prayer'
import { Route as AuthenticatedPetRouteImport } from './routes/_authenticated/pet'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOfflineQueueRouteImport } from './routes/_authenticated/offline-queue'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMoodRouteImport } from './routes/_authenticated/mood'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedMealplanRouteImport } from './routes/_authenticated/mealplan'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedHeatmapRouteImport } from './routes/_authenticated/heatmap'
import { Route as AuthenticatedHealthImportRouteImport } from './routes/_authenticated/health-import'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedFoodsRouteImport } from './routes/_authenticated/foods'
import { Route as AuthenticatedFoodRouteImport } from './routes/_authenticated/food'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedArticlesRouteImport } from './routes/_authenticated/articles'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat.stream'
import { Route as AuthenticatedStoriesIdRouteImport } from './routes/_authenticated/stories.$id'
import { Route as AuthenticatedScanVoiceRouteImport } from './routes/_authenticated/scan.voice'
import { Route as AuthenticatedScanRecipeRouteImport } from './routes/_authenticated/scan.recipe'
import { Route as AuthenticatedScanMenuRouteImport } from './routes/_authenticated/scan.menu'
import { Route as AuthenticatedScanHistoryRouteImport } from './routes/_authenticated/scan.history'
import { Route as AuthenticatedScanBarcodeRouteImport } from './routes/_authenticated/scan.barcode'
import { Route as AuthenticatedReportsWorkoutMatchRouteImport } from './routes/_authenticated/reports.workout-match'
import { Route as AuthenticatedReportsSleepMealRouteImport } from './routes/_authenticated/reports.sleep-meal'
import { Route as AuthenticatedReportsNutritionRouteImport } from './routes/_authenticated/reports.nutrition'
import { Route as AuthenticatedReportsMoodRouteImport } from './routes/_authenticated/reports.mood'
import { Route as AuthenticatedReportsHydrationRouteImport } from './routes/_authenticated/reports.hydration'
import { Route as AuthenticatedReportsGalleryRouteImport } from './routes/_authenticated/reports.gallery'
import { Route as AuthenticatedReportsExportRouteImport } from './routes/_authenticated/reports.export'
import { Route as AuthenticatedReportsCompareRouteImport } from './routes/_authenticated/reports.compare'
import { Route as AuthenticatedRecipesSavedRouteImport } from './routes/_authenticated/recipes.saved'
import { Route as AuthenticatedRecipesRecommendationsRouteImport } from './routes/_authenticated/recipes.recommendations'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'
import { Route as AuthenticatedQuizDailyRouteImport } from './routes/_authenticated/quiz.daily'
import { Route as AuthenticatedProfileScanStatsRouteImport } from './routes/_authenticated/profile.scan-stats'
import { Route as AuthenticatedProfilePrivacyRouteImport } from './routes/_authenticated/profile.privacy'
import { Route as AuthenticatedMealplanGroceryRouteImport } from './routes/_authenticated/mealplan.grocery'
import { Route as AuthenticatedCoachMealsRouteImport } from './routes/_authenticated/coach.meals'
import { Route as AuthenticatedChallengesDailyRouteImport } from './routes/_authenticated/challenges.daily'
import { Route as ApiWearableGoogleFitCallbackRouteImport } from './routes/api/wearable.google-fit.callback'
import { Route as ApiPublicHooksWeeklyAiReportRouteImport } from './routes/api/public/hooks/weekly-ai-report'
import { Route as ApiPublicHooksRecipesTrendingSnapshotRouteImport } from './routes/api/public/hooks/recipes-trending-snapshot'
import { Route as ApiPublicHooksNotificationSchedulerRouteImport } from './routes/api/public/hooks/notification-scheduler'
import { Route as ApiPublicHooksDailyCoachRouteImport } from './routes/api/public/hooks/daily-coach'
import { Route as AuthenticatedRecipesIdRemixRouteImport } from './routes/_authenticated/recipes.$id.remix'
import { Route as AuthenticatedProfilePublicIdRouteImport } from './routes/_authenticated/profile.public.$id'
import { Route as AuthenticatedGroupsIdMealsRouteImport } from './routes/_authenticated/groups.$id.meals'
import { Route as AuthenticatedGroupsIdLeaderboardRouteImport } from './routes/_authenticated/groups.$id.leaderboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutRoute = AuthenticatedWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeightRoute = AuthenticatedWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWearableRoute = AuthenticatedWearableRouteImport.update({
  id: '/wearable',
  path: '/wearable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaterRoute = AuthenticatedWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVitalsRoute = AuthenticatedVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSleepRoute = AuthenticatedSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReverseCalorieRoute =
  AuthenticatedReverseCalorieRouteImport.update({
    id: '/reverse-calorie',
    path: '/reverse-calorie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecommendationsRoute =
  AuthenticatedRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerRoute = AuthenticatedPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetRoute = AuthenticatedPetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfflineQueueRoute =
  AuthenticatedOfflineQueueRouteImport.update({
    id: '/offline-queue',
    path: '/offline-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMoodRoute = AuthenticatedMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMealplanRoute = AuthenticatedMealplanRouteImport.update({
  id: '/mealplan',
  path: '/mealplan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeatmapRoute = AuthenticatedHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthImportRoute =
  AuthenticatedHealthImportRouteImport.update({
    id: '/health-import',
    path: '/health-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodsRoute = AuthenticatedFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodRoute = AuthenticatedFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArticlesRoute = AuthenticatedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoriesIdRoute = AuthenticatedStoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStoriesRoute,
} as any)
const AuthenticatedScanVoiceRoute = AuthenticatedScanVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedScanRoute,
} as any)
const AuthenticatedScanRecipeRoute = AuthenticatedScanRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => AuthenticatedScanRoute,
} as any)
const AuthenticatedScanMenuRoute = AuthenticatedScanMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedScanRoute,
} as any)
const AuthenticatedScanHistoryRoute =
  AuthenticatedScanHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedScanRoute,
  } as any)
const AuthenticatedScanBarcodeRoute =
  AuthenticatedScanBarcodeRouteImport.update({
    id: '/barcode',
    path: '/barcode',
    getParentRoute: () => AuthenticatedScanRoute,
  } as any)
const AuthenticatedReportsWorkoutMatchRoute =
  AuthenticatedReportsWorkoutMatchRouteImport.update({
    id: '/workout-match',
    path: '/workout-match',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsSleepMealRoute =
  AuthenticatedReportsSleepMealRouteImport.update({
    id: '/sleep-meal',
    path: '/sleep-meal',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsNutritionRoute =
  AuthenticatedReportsNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsMoodRoute =
  AuthenticatedReportsMoodRouteImport.update({
    id: '/mood',
    path: '/mood',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsHydrationRoute =
  AuthenticatedReportsHydrationRouteImport.update({
    id: '/hydration',
    path: '/hydration',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsGalleryRoute =
  AuthenticatedReportsGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsExportRoute =
  AuthenticatedReportsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCompareRoute =
  AuthenticatedReportsCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedRecipesSavedRoute =
  AuthenticatedRecipesSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedRecipesRoute,
  } as any)
const AuthenticatedRecipesRecommendationsRoute =
  AuthenticatedRecipesRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AuthenticatedRecipesRoute,
  } as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRecipesRoute,
} as any)
const AuthenticatedQuizDailyRoute = AuthenticatedQuizDailyRouteImport.update({
  id: '/quiz/daily',
  path: '/quiz/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileScanStatsRoute =
  AuthenticatedProfileScanStatsRouteImport.update({
    id: '/scan-stats',
    path: '/scan-stats',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePrivacyRoute =
  AuthenticatedProfilePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedMealplanGroceryRoute =
  AuthenticatedMealplanGroceryRouteImport.update({
    id: '/grocery',
    path: '/grocery',
    getParentRoute: () => AuthenticatedMealplanRoute,
  } as any)
const AuthenticatedCoachMealsRoute = AuthenticatedCoachMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedChallengesDailyRoute =
  AuthenticatedChallengesDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const ApiWearableGoogleFitCallbackRoute =
  ApiWearableGoogleFitCallbackRouteImport.update({
    id: '/api/wearable/google-fit/callback',
    path: '/api/wearable/google-fit/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyAiReportRoute =
  ApiPublicHooksWeeklyAiReportRouteImport.update({
    id: '/api/public/hooks/weekly-ai-report',
    path: '/api/public/hooks/weekly-ai-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecipesTrendingSnapshotRoute =
  ApiPublicHooksRecipesTrendingSnapshotRouteImport.update({
    id: '/api/public/hooks/recipes-trending-snapshot',
    path: '/api/public/hooks/recipes-trending-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationSchedulerRoute =
  ApiPublicHooksNotificationSchedulerRouteImport.update({
    id: '/api/public/hooks/notification-scheduler',
    path: '/api/public/hooks/notification-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyCoachRoute =
  ApiPublicHooksDailyCoachRouteImport.update({
    id: '/api/public/hooks/daily-coach',
    path: '/api/public/hooks/daily-coach',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRecipesIdRemixRoute =
  AuthenticatedRecipesIdRemixRouteImport.update({
    id: '/remix',
    path: '/remix',
    getParentRoute: () => AuthenticatedRecipesIdRoute,
  } as any)
const AuthenticatedProfilePublicIdRoute =
  AuthenticatedProfilePublicIdRouteImport.update({
    id: '/public/$id',
    path: '/public/$id',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedGroupsIdMealsRoute =
  AuthenticatedGroupsIdMealsRouteImport.update({
    id: '/$id/meals',
    path: '/$id/meals',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedGroupsIdLeaderboardRoute =
  AuthenticatedGroupsIdLeaderboardRouteImport.update({
    id: '/$id/leaderboard',
    path: '/$id/leaderboard',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/food': typeof AuthenticatedFoodRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/health-import': typeof AuthenticatedHealthImportRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/mealplan': typeof AuthenticatedMealplanRouteWithChildren
  '/medications': typeof AuthenticatedMedicationsRoute
  '/mood': typeof AuthenticatedMoodRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offline-queue': typeof AuthenticatedOfflineQueueRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pet': typeof AuthenticatedPetRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/reverse-calorie': typeof AuthenticatedReverseCalorieRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/sleep': typeof AuthenticatedSleepRoute
  '/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/water': typeof AuthenticatedWaterRoute
  '/wearable': typeof AuthenticatedWearableRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/challenges/daily': typeof AuthenticatedChallengesDailyRoute
  '/coach/meals': typeof AuthenticatedCoachMealsRoute
  '/mealplan/grocery': typeof AuthenticatedMealplanGroceryRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/scan-stats': typeof AuthenticatedProfileScanStatsRoute
  '/quiz/daily': typeof AuthenticatedQuizDailyRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRouteWithChildren
  '/recipes/recommendations': typeof AuthenticatedRecipesRecommendationsRoute
  '/recipes/saved': typeof AuthenticatedRecipesSavedRoute
  '/reports/compare': typeof AuthenticatedReportsCompareRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/reports/gallery': typeof AuthenticatedReportsGalleryRoute
  '/reports/hydration': typeof AuthenticatedReportsHydrationRoute
  '/reports/mood': typeof AuthenticatedReportsMoodRoute
  '/reports/nutrition': typeof AuthenticatedReportsNutritionRoute
  '/reports/sleep-meal': typeof AuthenticatedReportsSleepMealRoute
  '/reports/workout-match': typeof AuthenticatedReportsWorkoutMatchRoute
  '/scan/barcode': typeof AuthenticatedScanBarcodeRoute
  '/scan/history': typeof AuthenticatedScanHistoryRoute
  '/scan/menu': typeof AuthenticatedScanMenuRoute
  '/scan/recipe': typeof AuthenticatedScanRecipeRoute
  '/scan/voice': typeof AuthenticatedScanVoiceRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/groups/$id/leaderboard': typeof AuthenticatedGroupsIdLeaderboardRoute
  '/groups/$id/meals': typeof AuthenticatedGroupsIdMealsRoute
  '/profile/public/$id': typeof AuthenticatedProfilePublicIdRoute
  '/recipes/$id/remix': typeof AuthenticatedRecipesIdRemixRoute
  '/api/public/hooks/daily-coach': typeof ApiPublicHooksDailyCoachRoute
  '/api/public/hooks/notification-scheduler': typeof ApiPublicHooksNotificationSchedulerRoute
  '/api/public/hooks/recipes-trending-snapshot': typeof ApiPublicHooksRecipesTrendingSnapshotRoute
  '/api/public/hooks/weekly-ai-report': typeof ApiPublicHooksWeeklyAiReportRoute
  '/api/wearable/google-fit/callback': typeof ApiWearableGoogleFitCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/articles': typeof AuthenticatedArticlesRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/food': typeof AuthenticatedFoodRoute
  '/foods': typeof AuthenticatedFoodsRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/health-import': typeof AuthenticatedHealthImportRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/mealplan': typeof AuthenticatedMealplanRouteWithChildren
  '/medications': typeof AuthenticatedMedicationsRoute
  '/mood': typeof AuthenticatedMoodRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offline-queue': typeof AuthenticatedOfflineQueueRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pet': typeof AuthenticatedPetRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/recommendations': typeof AuthenticatedRecommendationsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/reverse-calorie': typeof AuthenticatedReverseCalorieRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/sleep': typeof AuthenticatedSleepRoute
  '/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/water': typeof AuthenticatedWaterRoute
  '/wearable': typeof AuthenticatedWearableRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/challenges/daily': typeof AuthenticatedChallengesDailyRoute
  '/coach/meals': typeof AuthenticatedCoachMealsRoute
  '/mealplan/grocery': typeof AuthenticatedMealplanGroceryRoute
  '/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/profile/scan-stats': typeof AuthenticatedProfileScanStatsRoute
  '/quiz/daily': typeof AuthenticatedQuizDailyRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRouteWithChildren
  '/recipes/recommendations': typeof AuthenticatedRecipesRecommendationsRoute
  '/recipes/saved': typeof AuthenticatedRecipesSavedRoute
  '/reports/compare': typeof AuthenticatedReportsCompareRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/reports/gallery': typeof AuthenticatedReportsGalleryRoute
  '/reports/hydration': typeof AuthenticatedReportsHydrationRoute
  '/reports/mood': typeof AuthenticatedReportsMoodRoute
  '/reports/nutrition': typeof AuthenticatedReportsNutritionRoute
  '/reports/sleep-meal': typeof AuthenticatedReportsSleepMealRoute
  '/reports/workout-match': typeof AuthenticatedReportsWorkoutMatchRoute
  '/scan/barcode': typeof AuthenticatedScanBarcodeRoute
  '/scan/history': typeof AuthenticatedScanHistoryRoute
  '/scan/menu': typeof AuthenticatedScanMenuRoute
  '/scan/recipe': typeof AuthenticatedScanRecipeRoute
  '/scan/voice': typeof AuthenticatedScanVoiceRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/groups/$id/leaderboard': typeof AuthenticatedGroupsIdLeaderboardRoute
  '/groups/$id/meals': typeof AuthenticatedGroupsIdMealsRoute
  '/profile/public/$id': typeof AuthenticatedProfilePublicIdRoute
  '/recipes/$id/remix': typeof AuthenticatedRecipesIdRemixRoute
  '/api/public/hooks/daily-coach': typeof ApiPublicHooksDailyCoachRoute
  '/api/public/hooks/notification-scheduler': typeof ApiPublicHooksNotificationSchedulerRoute
  '/api/public/hooks/recipes-trending-snapshot': typeof ApiPublicHooksRecipesTrendingSnapshotRoute
  '/api/public/hooks/weekly-ai-report': typeof ApiPublicHooksWeeklyAiReportRoute
  '/api/wearable/google-fit/callback': typeof ApiWearableGoogleFitCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/articles': typeof AuthenticatedArticlesRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/food': typeof AuthenticatedFoodRoute
  '/_authenticated/foods': typeof AuthenticatedFoodsRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/health-import': typeof AuthenticatedHealthImportRoute
  '/_authenticated/heatmap': typeof AuthenticatedHeatmapRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/mealplan': typeof AuthenticatedMealplanRouteWithChildren
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/mood': typeof AuthenticatedMoodRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offline-queue': typeof AuthenticatedOfflineQueueRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pet': typeof AuthenticatedPetRoute
  '/_authenticated/prayer': typeof AuthenticatedPrayerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/_authenticated/recommendations': typeof AuthenticatedRecommendationsRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/reverse-calorie': typeof AuthenticatedReverseCalorieRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRouteWithChildren
  '/_authenticated/sleep': typeof AuthenticatedSleepRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRouteWithChildren
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/vitals': typeof AuthenticatedVitalsRoute
  '/_authenticated/water': typeof AuthenticatedWaterRoute
  '/_authenticated/wearable': typeof AuthenticatedWearableRoute
  '/_authenticated/weight': typeof AuthenticatedWeightRoute
  '/_authenticated/workout': typeof AuthenticatedWorkoutRoute
  '/_authenticated/challenges/daily': typeof AuthenticatedChallengesDailyRoute
  '/_authenticated/coach/meals': typeof AuthenticatedCoachMealsRoute
  '/_authenticated/mealplan/grocery': typeof AuthenticatedMealplanGroceryRoute
  '/_authenticated/profile/privacy': typeof AuthenticatedProfilePrivacyRoute
  '/_authenticated/profile/scan-stats': typeof AuthenticatedProfileScanStatsRoute
  '/_authenticated/quiz/daily': typeof AuthenticatedQuizDailyRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRouteWithChildren
  '/_authenticated/recipes/recommendations': typeof AuthenticatedRecipesRecommendationsRoute
  '/_authenticated/recipes/saved': typeof AuthenticatedRecipesSavedRoute
  '/_authenticated/reports/compare': typeof AuthenticatedReportsCompareRoute
  '/_authenticated/reports/export': typeof AuthenticatedReportsExportRoute
  '/_authenticated/reports/gallery': typeof AuthenticatedReportsGalleryRoute
  '/_authenticated/reports/hydration': typeof AuthenticatedReportsHydrationRoute
  '/_authenticated/reports/mood': typeof AuthenticatedReportsMoodRoute
  '/_authenticated/reports/nutrition': typeof AuthenticatedReportsNutritionRoute
  '/_authenticated/reports/sleep-meal': typeof AuthenticatedReportsSleepMealRoute
  '/_authenticated/reports/workout-match': typeof AuthenticatedReportsWorkoutMatchRoute
  '/_authenticated/scan/barcode': typeof AuthenticatedScanBarcodeRoute
  '/_authenticated/scan/history': typeof AuthenticatedScanHistoryRoute
  '/_authenticated/scan/menu': typeof AuthenticatedScanMenuRoute
  '/_authenticated/scan/recipe': typeof AuthenticatedScanRecipeRoute
  '/_authenticated/scan/voice': typeof AuthenticatedScanVoiceRoute
  '/_authenticated/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/_authenticated/groups/$id/leaderboard': typeof AuthenticatedGroupsIdLeaderboardRoute
  '/_authenticated/groups/$id/meals': typeof AuthenticatedGroupsIdMealsRoute
  '/_authenticated/profile/public/$id': typeof AuthenticatedProfilePublicIdRoute
  '/_authenticated/recipes/$id/remix': typeof AuthenticatedRecipesIdRemixRoute
  '/api/public/hooks/daily-coach': typeof ApiPublicHooksDailyCoachRoute
  '/api/public/hooks/notification-scheduler': typeof ApiPublicHooksNotificationSchedulerRoute
  '/api/public/hooks/recipes-trending-snapshot': typeof ApiPublicHooksRecipesTrendingSnapshotRoute
  '/api/public/hooks/weekly-ai-report': typeof ApiPublicHooksWeeklyAiReportRoute
  '/api/wearable/google-fit/callback': typeof ApiWearableGoogleFitCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/articles'
    | '/backup'
    | '/challenges'
    | '/chat'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/discover'
    | '/doctor'
    | '/family'
    | '/fasting'
    | '/food'
    | '/foods'
    | '/groups'
    | '/health-import'
    | '/heatmap'
    | '/insights'
    | '/leaderboard'
    | '/mealplan'
    | '/medications'
    | '/mood'
    | '/notifications'
    | '/offline-queue'
    | '/onboarding'
    | '/pet'
    | '/prayer'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/recommendations'
    | '/referrals'
    | '/reminders'
    | '/reports'
    | '/reverse-calorie'
    | '/rewards'
    | '/scan'
    | '/sleep'
    | '/stories'
    | '/subscription'
    | '/vitals'
    | '/water'
    | '/wearable'
    | '/weight'
    | '/workout'
    | '/challenges/daily'
    | '/coach/meals'
    | '/mealplan/grocery'
    | '/profile/privacy'
    | '/profile/scan-stats'
    | '/quiz/daily'
    | '/recipes/$id'
    | '/recipes/recommendations'
    | '/recipes/saved'
    | '/reports/compare'
    | '/reports/export'
    | '/reports/gallery'
    | '/reports/hydration'
    | '/reports/mood'
    | '/reports/nutrition'
    | '/reports/sleep-meal'
    | '/reports/workout-match'
    | '/scan/barcode'
    | '/scan/history'
    | '/scan/menu'
    | '/scan/recipe'
    | '/scan/voice'
    | '/stories/$id'
    | '/api/chat/stream'
    | '/groups/$id/leaderboard'
    | '/groups/$id/meals'
    | '/profile/public/$id'
    | '/recipes/$id/remix'
    | '/api/public/hooks/daily-coach'
    | '/api/public/hooks/notification-scheduler'
    | '/api/public/hooks/recipes-trending-snapshot'
    | '/api/public/hooks/weekly-ai-report'
    | '/api/wearable/google-fit/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/articles'
    | '/backup'
    | '/challenges'
    | '/chat'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/discover'
    | '/doctor'
    | '/family'
    | '/fasting'
    | '/food'
    | '/foods'
    | '/groups'
    | '/health-import'
    | '/heatmap'
    | '/insights'
    | '/leaderboard'
    | '/mealplan'
    | '/medications'
    | '/mood'
    | '/notifications'
    | '/offline-queue'
    | '/onboarding'
    | '/pet'
    | '/prayer'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/recommendations'
    | '/referrals'
    | '/reminders'
    | '/reports'
    | '/reverse-calorie'
    | '/rewards'
    | '/scan'
    | '/sleep'
    | '/stories'
    | '/subscription'
    | '/vitals'
    | '/water'
    | '/wearable'
    | '/weight'
    | '/workout'
    | '/challenges/daily'
    | '/coach/meals'
    | '/mealplan/grocery'
    | '/profile/privacy'
    | '/profile/scan-stats'
    | '/quiz/daily'
    | '/recipes/$id'
    | '/recipes/recommendations'
    | '/recipes/saved'
    | '/reports/compare'
    | '/reports/export'
    | '/reports/gallery'
    | '/reports/hydration'
    | '/reports/mood'
    | '/reports/nutrition'
    | '/reports/sleep-meal'
    | '/reports/workout-match'
    | '/scan/barcode'
    | '/scan/history'
    | '/scan/menu'
    | '/scan/recipe'
    | '/scan/voice'
    | '/stories/$id'
    | '/api/chat/stream'
    | '/groups/$id/leaderboard'
    | '/groups/$id/meals'
    | '/profile/public/$id'
    | '/recipes/$id/remix'
    | '/api/public/hooks/daily-coach'
    | '/api/public/hooks/notification-scheduler'
    | '/api/public/hooks/recipes-trending-snapshot'
    | '/api/public/hooks/weekly-ai-report'
    | '/api/wearable/google-fit/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/articles'
    | '/_authenticated/backup'
    | '/_authenticated/challenges'
    | '/_authenticated/chat'
    | '/_authenticated/coach'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/doctor'
    | '/_authenticated/family'
    | '/_authenticated/fasting'
    | '/_authenticated/food'
    | '/_authenticated/foods'
    | '/_authenticated/groups'
    | '/_authenticated/health-import'
    | '/_authenticated/heatmap'
    | '/_authenticated/insights'
    | '/_authenticated/leaderboard'
    | '/_authenticated/mealplan'
    | '/_authenticated/medications'
    | '/_authenticated/mood'
    | '/_authenticated/notifications'
    | '/_authenticated/offline-queue'
    | '/_authenticated/onboarding'
    | '/_authenticated/pet'
    | '/_authenticated/prayer'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/recipes'
    | '/_authenticated/recommendations'
    | '/_authenticated/referrals'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/reverse-calorie'
    | '/_authenticated/rewards'
    | '/_authenticated/scan'
    | '/_authenticated/sleep'
    | '/_authenticated/stories'
    | '/_authenticated/subscription'
    | '/_authenticated/vitals'
    | '/_authenticated/water'
    | '/_authenticated/wearable'
    | '/_authenticated/weight'
    | '/_authenticated/workout'
    | '/_authenticated/challenges/daily'
    | '/_authenticated/coach/meals'
    | '/_authenticated/mealplan/grocery'
    | '/_authenticated/profile/privacy'
    | '/_authenticated/profile/scan-stats'
    | '/_authenticated/quiz/daily'
    | '/_authenticated/recipes/$id'
    | '/_authenticated/recipes/recommendations'
    | '/_authenticated/recipes/saved'
    | '/_authenticated/reports/compare'
    | '/_authenticated/reports/export'
    | '/_authenticated/reports/gallery'
    | '/_authenticated/reports/hydration'
    | '/_authenticated/reports/mood'
    | '/_authenticated/reports/nutrition'
    | '/_authenticated/reports/sleep-meal'
    | '/_authenticated/reports/workout-match'
    | '/_authenticated/scan/barcode'
    | '/_authenticated/scan/history'
    | '/_authenticated/scan/menu'
    | '/_authenticated/scan/recipe'
    | '/_authenticated/scan/voice'
    | '/_authenticated/stories/$id'
    | '/api/chat/stream'
    | '/_authenticated/groups/$id/leaderboard'
    | '/_authenticated/groups/$id/meals'
    | '/_authenticated/profile/public/$id'
    | '/_authenticated/recipes/$id/remix'
    | '/api/public/hooks/daily-coach'
    | '/api/public/hooks/notification-scheduler'
    | '/api/public/hooks/recipes-trending-snapshot'
    | '/api/public/hooks/weekly-ai-report'
    | '/api/wearable/google-fit/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiPublicHooksDailyCoachRoute: typeof ApiPublicHooksDailyCoachRoute
  ApiPublicHooksNotificationSchedulerRoute: typeof ApiPublicHooksNotificationSchedulerRoute
  ApiPublicHooksRecipesTrendingSnapshotRoute: typeof ApiPublicHooksRecipesTrendingSnapshotRoute
  ApiPublicHooksWeeklyAiReportRoute: typeof ApiPublicHooksWeeklyAiReportRoute
  ApiWearableGoogleFitCallbackRoute: typeof ApiWearableGoogleFitCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout': {
      id: '/_authenticated/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthenticatedWorkoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weight': {
      id: '/_authenticated/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthenticatedWeightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wearable': {
      id: '/_authenticated/wearable'
      path: '/wearable'
      fullPath: '/wearable'
      preLoaderRoute: typeof AuthenticatedWearableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/water': {
      id: '/_authenticated/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof AuthenticatedWaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vitals': {
      id: '/_authenticated/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthenticatedVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sleep': {
      id: '/_authenticated/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof AuthenticatedSleepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reverse-calorie': {
      id: '/_authenticated/reverse-calorie'
      path: '/reverse-calorie'
      fullPath: '/reverse-calorie'
      preLoaderRoute: typeof AuthenticatedReverseCalorieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recommendations': {
      id: '/_authenticated/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AuthenticatedRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer': {
      id: '/_authenticated/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof AuthenticatedPrayerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet': {
      id: '/_authenticated/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof AuthenticatedPetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offline-queue': {
      id: '/_authenticated/offline-queue'
      path: '/offline-queue'
      fullPath: '/offline-queue'
      preLoaderRoute: typeof AuthenticatedOfflineQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mood': {
      id: '/_authenticated/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof AuthenticatedMoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mealplan': {
      id: '/_authenticated/mealplan'
      path: '/mealplan'
      fullPath: '/mealplan'
      preLoaderRoute: typeof AuthenticatedMealplanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heatmap': {
      id: '/_authenticated/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AuthenticatedHeatmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-import': {
      id: '/_authenticated/health-import'
      path: '/health-import'
      fullPath: '/health-import'
      preLoaderRoute: typeof AuthenticatedHealthImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foods': {
      id: '/_authenticated/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof AuthenticatedFoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food': {
      id: '/_authenticated/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AuthenticatedFoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/articles': {
      id: '/_authenticated/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedArticlesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stories/$id': {
      id: '/_authenticated/stories/$id'
      path: '/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof AuthenticatedStoriesIdRouteImport
      parentRoute: typeof AuthenticatedStoriesRoute
    }
    '/_authenticated/scan/voice': {
      id: '/_authenticated/scan/voice'
      path: '/voice'
      fullPath: '/scan/voice'
      preLoaderRoute: typeof AuthenticatedScanVoiceRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/scan/recipe': {
      id: '/_authenticated/scan/recipe'
      path: '/recipe'
      fullPath: '/scan/recipe'
      preLoaderRoute: typeof AuthenticatedScanRecipeRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/scan/menu': {
      id: '/_authenticated/scan/menu'
      path: '/menu'
      fullPath: '/scan/menu'
      preLoaderRoute: typeof AuthenticatedScanMenuRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/scan/history': {
      id: '/_authenticated/scan/history'
      path: '/history'
      fullPath: '/scan/history'
      preLoaderRoute: typeof AuthenticatedScanHistoryRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/scan/barcode': {
      id: '/_authenticated/scan/barcode'
      path: '/barcode'
      fullPath: '/scan/barcode'
      preLoaderRoute: typeof AuthenticatedScanBarcodeRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/_authenticated/reports/workout-match': {
      id: '/_authenticated/reports/workout-match'
      path: '/workout-match'
      fullPath: '/reports/workout-match'
      preLoaderRoute: typeof AuthenticatedReportsWorkoutMatchRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/sleep-meal': {
      id: '/_authenticated/reports/sleep-meal'
      path: '/sleep-meal'
      fullPath: '/reports/sleep-meal'
      preLoaderRoute: typeof AuthenticatedReportsSleepMealRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/nutrition': {
      id: '/_authenticated/reports/nutrition'
      path: '/nutrition'
      fullPath: '/reports/nutrition'
      preLoaderRoute: typeof AuthenticatedReportsNutritionRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/mood': {
      id: '/_authenticated/reports/mood'
      path: '/mood'
      fullPath: '/reports/mood'
      preLoaderRoute: typeof AuthenticatedReportsMoodRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/hydration': {
      id: '/_authenticated/reports/hydration'
      path: '/hydration'
      fullPath: '/reports/hydration'
      preLoaderRoute: typeof AuthenticatedReportsHydrationRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/gallery': {
      id: '/_authenticated/reports/gallery'
      path: '/gallery'
      fullPath: '/reports/gallery'
      preLoaderRoute: typeof AuthenticatedReportsGalleryRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/export': {
      id: '/_authenticated/reports/export'
      path: '/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AuthenticatedReportsExportRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/compare': {
      id: '/_authenticated/reports/compare'
      path: '/compare'
      fullPath: '/reports/compare'
      preLoaderRoute: typeof AuthenticatedReportsCompareRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/recipes/saved': {
      id: '/_authenticated/recipes/saved'
      path: '/saved'
      fullPath: '/recipes/saved'
      preLoaderRoute: typeof AuthenticatedRecipesSavedRouteImport
      parentRoute: typeof AuthenticatedRecipesRoute
    }
    '/_authenticated/recipes/recommendations': {
      id: '/_authenticated/recipes/recommendations'
      path: '/recommendations'
      fullPath: '/recipes/recommendations'
      preLoaderRoute: typeof AuthenticatedRecipesRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRecipesRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRecipesRoute
    }
    '/_authenticated/quiz/daily': {
      id: '/_authenticated/quiz/daily'
      path: '/quiz/daily'
      fullPath: '/quiz/daily'
      preLoaderRoute: typeof AuthenticatedQuizDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/scan-stats': {
      id: '/_authenticated/profile/scan-stats'
      path: '/scan-stats'
      fullPath: '/profile/scan-stats'
      preLoaderRoute: typeof AuthenticatedProfileScanStatsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/privacy': {
      id: '/_authenticated/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AuthenticatedProfilePrivacyRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/mealplan/grocery': {
      id: '/_authenticated/mealplan/grocery'
      path: '/grocery'
      fullPath: '/mealplan/grocery'
      preLoaderRoute: typeof AuthenticatedMealplanGroceryRouteImport
      parentRoute: typeof AuthenticatedMealplanRoute
    }
    '/_authenticated/coach/meals': {
      id: '/_authenticated/coach/meals'
      path: '/meals'
      fullPath: '/coach/meals'
      preLoaderRoute: typeof AuthenticatedCoachMealsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/challenges/daily': {
      id: '/_authenticated/challenges/daily'
      path: '/daily'
      fullPath: '/challenges/daily'
      preLoaderRoute: typeof AuthenticatedChallengesDailyRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/api/wearable/google-fit/callback': {
      id: '/api/wearable/google-fit/callback'
      path: '/api/wearable/google-fit/callback'
      fullPath: '/api/wearable/google-fit/callback'
      preLoaderRoute: typeof ApiWearableGoogleFitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-ai-report': {
      id: '/api/public/hooks/weekly-ai-report'
      path: '/api/public/hooks/weekly-ai-report'
      fullPath: '/api/public/hooks/weekly-ai-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyAiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recipes-trending-snapshot': {
      id: '/api/public/hooks/recipes-trending-snapshot'
      path: '/api/public/hooks/recipes-trending-snapshot'
      fullPath: '/api/public/hooks/recipes-trending-snapshot'
      preLoaderRoute: typeof ApiPublicHooksRecipesTrendingSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-scheduler': {
      id: '/api/public/hooks/notification-scheduler'
      path: '/api/public/hooks/notification-scheduler'
      fullPath: '/api/public/hooks/notification-scheduler'
      preLoaderRoute: typeof ApiPublicHooksNotificationSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-coach': {
      id: '/api/public/hooks/daily-coach'
      path: '/api/public/hooks/daily-coach'
      fullPath: '/api/public/hooks/daily-coach'
      preLoaderRoute: typeof ApiPublicHooksDailyCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes/$id/remix': {
      id: '/_authenticated/recipes/$id/remix'
      path: '/remix'
      fullPath: '/recipes/$id/remix'
      preLoaderRoute: typeof AuthenticatedRecipesIdRemixRouteImport
      parentRoute: typeof AuthenticatedRecipesIdRoute
    }
    '/_authenticated/profile/public/$id': {
      id: '/_authenticated/profile/public/$id'
      path: '/public/$id'
      fullPath: '/profile/public/$id'
      preLoaderRoute: typeof AuthenticatedProfilePublicIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/groups/$id/meals': {
      id: '/_authenticated/groups/$id/meals'
      path: '/$id/meals'
      fullPath: '/groups/$id/meals'
      preLoaderRoute: typeof AuthenticatedGroupsIdMealsRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/groups/$id/leaderboard': {
      id: '/_authenticated/groups/$id/leaderboard'
      path: '/$id/leaderboard'
      fullPath: '/groups/$id/leaderboard'
      preLoaderRoute: typeof AuthenticatedGroupsIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
  }
}

interface AuthenticatedChallengesRouteChildren {
  AuthenticatedChallengesDailyRoute: typeof AuthenticatedChallengesDailyRoute
}

const AuthenticatedChallengesRouteChildren: AuthenticatedChallengesRouteChildren =
  {
    AuthenticatedChallengesDailyRoute: AuthenticatedChallengesDailyRoute,
  }

const AuthenticatedChallengesRouteWithChildren =
  AuthenticatedChallengesRoute._addFileChildren(
    AuthenticatedChallengesRouteChildren,
  )

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachMealsRoute: typeof AuthenticatedCoachMealsRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachMealsRoute: AuthenticatedCoachMealsRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsIdLeaderboardRoute: typeof AuthenticatedGroupsIdLeaderboardRoute
  AuthenticatedGroupsIdMealsRoute: typeof AuthenticatedGroupsIdMealsRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsIdLeaderboardRoute: AuthenticatedGroupsIdLeaderboardRoute,
  AuthenticatedGroupsIdMealsRoute: AuthenticatedGroupsIdMealsRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedMealplanRouteChildren {
  AuthenticatedMealplanGroceryRoute: typeof AuthenticatedMealplanGroceryRoute
}

const AuthenticatedMealplanRouteChildren: AuthenticatedMealplanRouteChildren = {
  AuthenticatedMealplanGroceryRoute: AuthenticatedMealplanGroceryRoute,
}

const AuthenticatedMealplanRouteWithChildren =
  AuthenticatedMealplanRoute._addFileChildren(
    AuthenticatedMealplanRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePrivacyRoute: typeof AuthenticatedProfilePrivacyRoute
  AuthenticatedProfileScanStatsRoute: typeof AuthenticatedProfileScanStatsRoute
  AuthenticatedProfilePublicIdRoute: typeof AuthenticatedProfilePublicIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePrivacyRoute: AuthenticatedProfilePrivacyRoute,
  AuthenticatedProfileScanStatsRoute: AuthenticatedProfileScanStatsRoute,
  AuthenticatedProfilePublicIdRoute: AuthenticatedProfilePublicIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRecipesIdRouteChildren {
  AuthenticatedRecipesIdRemixRoute: typeof AuthenticatedRecipesIdRemixRoute
}

const AuthenticatedRecipesIdRouteChildren: AuthenticatedRecipesIdRouteChildren =
  {
    AuthenticatedRecipesIdRemixRoute: AuthenticatedRecipesIdRemixRoute,
  }

const AuthenticatedRecipesIdRouteWithChildren =
  AuthenticatedRecipesIdRoute._addFileChildren(
    AuthenticatedRecipesIdRouteChildren,
  )

interface AuthenticatedRecipesRouteChildren {
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRouteWithChildren
  AuthenticatedRecipesRecommendationsRoute: typeof AuthenticatedRecipesRecommendationsRoute
  AuthenticatedRecipesSavedRoute: typeof AuthenticatedRecipesSavedRoute
}

const AuthenticatedRecipesRouteChildren: AuthenticatedRecipesRouteChildren = {
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRouteWithChildren,
  AuthenticatedRecipesRecommendationsRoute:
    AuthenticatedRecipesRecommendationsRoute,
  AuthenticatedRecipesSavedRoute: AuthenticatedRecipesSavedRoute,
}

const AuthenticatedRecipesRouteWithChildren =
  AuthenticatedRecipesRoute._addFileChildren(AuthenticatedRecipesRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsCompareRoute: typeof AuthenticatedReportsCompareRoute
  AuthenticatedReportsExportRoute: typeof AuthenticatedReportsExportRoute
  AuthenticatedReportsGalleryRoute: typeof AuthenticatedReportsGalleryRoute
  AuthenticatedReportsHydrationRoute: typeof AuthenticatedReportsHydrationRoute
  AuthenticatedReportsMoodRoute: typeof AuthenticatedReportsMoodRoute
  AuthenticatedReportsNutritionRoute: typeof AuthenticatedReportsNutritionRoute
  AuthenticatedReportsSleepMealRoute: typeof AuthenticatedReportsSleepMealRoute
  AuthenticatedReportsWorkoutMatchRoute: typeof AuthenticatedReportsWorkoutMatchRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsCompareRoute: AuthenticatedReportsCompareRoute,
  AuthenticatedReportsExportRoute: AuthenticatedReportsExportRoute,
  AuthenticatedReportsGalleryRoute: AuthenticatedReportsGalleryRoute,
  AuthenticatedReportsHydrationRoute: AuthenticatedReportsHydrationRoute,
  AuthenticatedReportsMoodRoute: AuthenticatedReportsMoodRoute,
  AuthenticatedReportsNutritionRoute: AuthenticatedReportsNutritionRoute,
  AuthenticatedReportsSleepMealRoute: AuthenticatedReportsSleepMealRoute,
  AuthenticatedReportsWorkoutMatchRoute: AuthenticatedReportsWorkoutMatchRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedScanRouteChildren {
  AuthenticatedScanBarcodeRoute: typeof AuthenticatedScanBarcodeRoute
  AuthenticatedScanHistoryRoute: typeof AuthenticatedScanHistoryRoute
  AuthenticatedScanMenuRoute: typeof AuthenticatedScanMenuRoute
  AuthenticatedScanRecipeRoute: typeof AuthenticatedScanRecipeRoute
  AuthenticatedScanVoiceRoute: typeof AuthenticatedScanVoiceRoute
}

const AuthenticatedScanRouteChildren: AuthenticatedScanRouteChildren = {
  AuthenticatedScanBarcodeRoute: AuthenticatedScanBarcodeRoute,
  AuthenticatedScanHistoryRoute: AuthenticatedScanHistoryRoute,
  AuthenticatedScanMenuRoute: AuthenticatedScanMenuRoute,
  AuthenticatedScanRecipeRoute: AuthenticatedScanRecipeRoute,
  AuthenticatedScanVoiceRoute: AuthenticatedScanVoiceRoute,
}

const AuthenticatedScanRouteWithChildren =
  AuthenticatedScanRoute._addFileChildren(AuthenticatedScanRouteChildren)

interface AuthenticatedStoriesRouteChildren {
  AuthenticatedStoriesIdRoute: typeof AuthenticatedStoriesIdRoute
}

const AuthenticatedStoriesRouteChildren: AuthenticatedStoriesRouteChildren = {
  AuthenticatedStoriesIdRoute: AuthenticatedStoriesIdRoute,
}

const AuthenticatedStoriesRouteWithChildren =
  AuthenticatedStoriesRoute._addFileChildren(AuthenticatedStoriesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedArticlesRoute: typeof AuthenticatedArticlesRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedFoodRoute: typeof AuthenticatedFoodRoute
  AuthenticatedFoodsRoute: typeof AuthenticatedFoodsRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedHealthImportRoute: typeof AuthenticatedHealthImportRoute
  AuthenticatedHeatmapRoute: typeof AuthenticatedHeatmapRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMealplanRoute: typeof AuthenticatedMealplanRouteWithChildren
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedMoodRoute: typeof AuthenticatedMoodRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOfflineQueueRoute: typeof AuthenticatedOfflineQueueRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPetRoute: typeof AuthenticatedPetRoute
  AuthenticatedPrayerRoute: typeof AuthenticatedPrayerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRouteWithChildren
  AuthenticatedRecommendationsRoute: typeof AuthenticatedRecommendationsRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedReverseCalorieRoute: typeof AuthenticatedReverseCalorieRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRouteWithChildren
  AuthenticatedSleepRoute: typeof AuthenticatedSleepRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRouteWithChildren
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedVitalsRoute: typeof AuthenticatedVitalsRoute
  AuthenticatedWaterRoute: typeof AuthenticatedWaterRoute
  AuthenticatedWearableRoute: typeof AuthenticatedWearableRoute
  AuthenticatedWeightRoute: typeof AuthenticatedWeightRoute
  AuthenticatedWorkoutRoute: typeof AuthenticatedWorkoutRoute
  AuthenticatedQuizDailyRoute: typeof AuthenticatedQuizDailyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedArticlesRoute: AuthenticatedArticlesRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedFoodRoute: AuthenticatedFoodRoute,
  AuthenticatedFoodsRoute: AuthenticatedFoodsRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedHealthImportRoute: AuthenticatedHealthImportRoute,
  AuthenticatedHeatmapRoute: AuthenticatedHeatmapRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMealplanRoute: AuthenticatedMealplanRouteWithChildren,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedMoodRoute: AuthenticatedMoodRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOfflineQueueRoute: AuthenticatedOfflineQueueRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPetRoute: AuthenticatedPetRoute,
  AuthenticatedPrayerRoute: AuthenticatedPrayerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRouteWithChildren,
  AuthenticatedRecommendationsRoute: AuthenticatedRecommendationsRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedReverseCalorieRoute: AuthenticatedReverseCalorieRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRouteWithChildren,
  AuthenticatedSleepRoute: AuthenticatedSleepRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRouteWithChildren,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedVitalsRoute: AuthenticatedVitalsRoute,
  AuthenticatedWaterRoute: AuthenticatedWaterRoute,
  AuthenticatedWearableRoute: AuthenticatedWearableRoute,
  AuthenticatedWeightRoute: AuthenticatedWeightRoute,
  AuthenticatedWorkoutRoute: AuthenticatedWorkoutRoute,
  AuthenticatedQuizDailyRoute: AuthenticatedQuizDailyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiPublicHooksDailyCoachRoute: ApiPublicHooksDailyCoachRoute,
  ApiPublicHooksNotificationSchedulerRoute:
    ApiPublicHooksNotificationSchedulerRoute,
  ApiPublicHooksRecipesTrendingSnapshotRoute:
    ApiPublicHooksRecipesTrendingSnapshotRoute,
  ApiPublicHooksWeeklyAiReportRoute: ApiPublicHooksWeeklyAiReportRoute,
  ApiWearableGoogleFitCallbackRoute: ApiWearableGoogleFitCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
