/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutRouteImport } from './routes/_authenticated/workout'
import { Route as AuthenticatedSleepRouteImport } from './routes/_authenticated/sleep'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrayerRouteImport } from './routes/_authenticated/prayer'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedMealplanRouteImport } from './routes/_authenticated/mealplan'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFoodRouteImport } from './routes/_authenticated/food'
import { Route as AuthenticatedFastingRouteImport } from './routes/_authenticated/fasting'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutRoute = AuthenticatedWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSleepRoute = AuthenticatedSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrayerRoute = AuthenticatedPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMealplanRoute = AuthenticatedMealplanRouteImport.update({
  id: '/mealplan',
  path: '/mealplan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodRoute = AuthenticatedFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFastingRoute = AuthenticatedFastingRouteImport.update({
  id: '/fasting',
  path: '/fasting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/food': typeof AuthenticatedFoodRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/mealplan': typeof AuthenticatedMealplanRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sleep': typeof AuthenticatedSleepRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fasting': typeof AuthenticatedFastingRoute
  '/food': typeof AuthenticatedFoodRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/mealplan': typeof AuthenticatedMealplanRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prayer': typeof AuthenticatedPrayerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sleep': typeof AuthenticatedSleepRoute
  '/workout': typeof AuthenticatedWorkoutRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fasting': typeof AuthenticatedFastingRoute
  '/_authenticated/food': typeof AuthenticatedFoodRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/mealplan': typeof AuthenticatedMealplanRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/prayer': typeof AuthenticatedPrayerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRouteWithChildren
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sleep': typeof AuthenticatedSleepRoute
  '/_authenticated/workout': typeof AuthenticatedWorkoutRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/fasting'
    | '/food'
    | '/leaderboard'
    | '/mealplan'
    | '/medications'
    | '/onboarding'
    | '/prayer'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/reminders'
    | '/reports'
    | '/sleep'
    | '/workout'
    | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/fasting'
    | '/food'
    | '/leaderboard'
    | '/mealplan'
    | '/medications'
    | '/onboarding'
    | '/prayer'
    | '/profile'
    | '/progress'
    | '/recipes'
    | '/reminders'
    | '/reports'
    | '/sleep'
    | '/workout'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/chat'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/fasting'
    | '/_authenticated/food'
    | '/_authenticated/leaderboard'
    | '/_authenticated/mealplan'
    | '/_authenticated/medications'
    | '/_authenticated/onboarding'
    | '/_authenticated/prayer'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/recipes'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/sleep'
    | '/_authenticated/workout'
    | '/_authenticated/recipes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workout': {
      id: '/_authenticated/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AuthenticatedWorkoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sleep': {
      id: '/_authenticated/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof AuthenticatedSleepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prayer': {
      id: '/_authenticated/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof AuthenticatedPrayerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mealplan': {
      id: '/_authenticated/mealplan'
      path: '/mealplan'
      fullPath: '/mealplan'
      preLoaderRoute: typeof AuthenticatedMealplanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food': {
      id: '/_authenticated/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AuthenticatedFoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fasting': {
      id: '/_authenticated/fasting'
      path: '/fasting'
      fullPath: '/fasting'
      preLoaderRoute: typeof AuthenticatedFastingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRecipesRoute
    }
  }
}

interface AuthenticatedRecipesRouteChildren {
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRoute
}

const AuthenticatedRecipesRouteChildren: AuthenticatedRecipesRouteChildren = {
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRoute,
}

const AuthenticatedRecipesRouteWithChildren =
  AuthenticatedRecipesRoute._addFileChildren(AuthenticatedRecipesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFastingRoute: typeof AuthenticatedFastingRoute
  AuthenticatedFoodRoute: typeof AuthenticatedFoodRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMealplanRoute: typeof AuthenticatedMealplanRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrayerRoute: typeof AuthenticatedPrayerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRouteWithChildren
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSleepRoute: typeof AuthenticatedSleepRoute
  AuthenticatedWorkoutRoute: typeof AuthenticatedWorkoutRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFastingRoute: AuthenticatedFastingRoute,
  AuthenticatedFoodRoute: AuthenticatedFoodRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMealplanRoute: AuthenticatedMealplanRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrayerRoute: AuthenticatedPrayerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRouteWithChildren,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSleepRoute: AuthenticatedSleepRoute,
  AuthenticatedWorkoutRoute: AuthenticatedWorkoutRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
