
-- Batch 6: SEO foods table for /kalori/$slug pages
CREATE TABLE public.seo_foods (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  serving_size TEXT NOT NULL DEFAULT '100 g',
  serving_grams NUMERIC NOT NULL DEFAULT 100,
  calories NUMERIC NOT NULL,
  protein_g NUMERIC NOT NULL DEFAULT 0,
  carbs_g NUMERIC NOT NULL DEFAULT 0,
  fat_g NUMERIC NOT NULL DEFAULT 0,
  fiber_g NUMERIC NOT NULL DEFAULT 0,
  sugar_g NUMERIC NOT NULL DEFAULT 0,
  sodium_mg NUMERIC NOT NULL DEFAULT 0,
  description TEXT,
  tags TEXT[] NOT NULL DEFAULT '{}',
  published BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX seo_foods_category_idx ON public.seo_foods(category) WHERE published;
CREATE INDEX seo_foods_published_idx ON public.seo_foods(published);

GRANT SELECT ON public.seo_foods TO anon, authenticated;
GRANT ALL ON public.seo_foods TO service_role;

ALTER TABLE public.seo_foods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read published foods"
  ON public.seo_foods FOR SELECT
  USING (published = true);

CREATE TRIGGER seo_foods_updated_at
  BEFORE UPDATE ON public.seo_foods
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Seed: 100 makanan Indonesia (kcal & makro per 100g, perkiraan TKPI/USDA)
INSERT INTO public.seo_foods (slug, name, category, calories, protein_g, carbs_g, fat_g, fiber_g, description, tags) VALUES
('nasi-putih', 'Nasi Putih', 'Karbohidrat', 130, 2.7, 28, 0.3, 0.4, 'Nasi putih matang dari beras putih, makanan pokok Indonesia.', ARRAY['pokok','beras']),
('nasi-merah', 'Nasi Merah', 'Karbohidrat', 110, 2.6, 23, 0.9, 1.8, 'Nasi merah lebih tinggi serat dan rendah indeks glikemik.', ARRAY['pokok','sehat','diet']),
('nasi-goreng', 'Nasi Goreng', 'Hidangan Utama', 186, 5, 24, 7, 1, 'Nasi goreng khas Indonesia dengan kecap dan bumbu.', ARRAY['hidangan','populer']),
('nasi-uduk', 'Nasi Uduk', 'Hidangan Utama', 175, 3.5, 28, 5.5, 0.6, 'Nasi gurih dimasak dengan santan dan rempah.', ARRAY['hidangan','santan']),
('bubur-ayam', 'Bubur Ayam', 'Hidangan Utama', 95, 5, 14, 2, 0.5, 'Bubur nasi dengan suwiran ayam, kerupuk, dan kecap.', ARRAY['sarapan']),
('mie-instan', 'Mie Instan', 'Hidangan Utama', 448, 9, 65, 17, 2, 'Mie instan rebus, tinggi natrium dan kalori.', ARRAY['instant']),
('mie-goreng', 'Mie Goreng', 'Hidangan Utama', 380, 8, 50, 15, 2, 'Mie goreng dengan bumbu kecap dan telur.', ARRAY['hidangan']),
('soto-ayam', 'Soto Ayam', 'Sup', 130, 12, 8, 6, 0.8, 'Sup ayam khas Indonesia dengan kunyit.', ARRAY['sup','ayam']),
('rawon', 'Rawon', 'Sup', 167, 14, 5, 10, 1, 'Sup daging hitam khas Jawa Timur dengan kluwek.', ARRAY['sup','daging']),
('rendang', 'Rendang', 'Hidangan Utama', 195, 22, 7, 9, 1.2, 'Daging sapi dimasak lama dengan santan dan rempah.', ARRAY['daging','santan','padang']),
('gulai', 'Gulai', 'Hidangan Utama', 170, 14, 5, 11, 1, 'Kari santan kuning khas Indonesia.', ARRAY['santan']),
('opor-ayam', 'Opor Ayam', 'Hidangan Utama', 165, 13, 4, 11, 0.5, 'Ayam dimasak dengan santan kuning ringan.', ARRAY['santan','ayam']),
('ayam-goreng', 'Ayam Goreng', 'Hidangan Utama', 246, 27, 0, 15, 0, 'Potongan ayam goreng berbumbu.', ARRAY['ayam','goreng']),
('ayam-bakar', 'Ayam Bakar', 'Hidangan Utama', 199, 25, 3, 9, 0.2, 'Ayam dibakar dengan kecap dan bumbu.', ARRAY['ayam','bakar']),
('sate-ayam', 'Sate Ayam', 'Hidangan Utama', 215, 23, 8, 11, 0.5, 'Sate ayam dengan bumbu kacang.', ARRAY['ayam','sate']),
('sate-kambing', 'Sate Kambing', 'Hidangan Utama', 263, 25, 4, 17, 0.3, 'Sate daging kambing dengan kecap.', ARRAY['kambing','sate']),
('gado-gado', 'Gado-Gado', 'Salad', 137, 6, 12, 8, 3, 'Salad sayur dengan saus kacang.', ARRAY['sayur','vegetarian']),
('pecel', 'Pecel', 'Salad', 130, 6, 11, 7, 3, 'Sayur rebus dengan sambal kacang.', ARRAY['sayur','vegetarian']),
('karedok', 'Karedok', 'Salad', 110, 5, 10, 6, 3, 'Salad sayur mentah khas Sunda dengan bumbu kacang.', ARRAY['sayur','mentah']),
('ketoprak', 'Ketoprak', 'Hidangan Utama', 180, 7, 22, 7, 2, 'Ketupat, tahu, bihun, dan tauge dengan bumbu kacang.', ARRAY['vegetarian']),
('tahu-goreng', 'Tahu Goreng', 'Lauk', 271, 17, 11, 20, 1, 'Tahu yang digoreng hingga keemasan.', ARRAY['vegetarian','protein']),
('tempe-goreng', 'Tempe Goreng', 'Lauk', 270, 19, 14, 17, 5, 'Tempe goreng renyah, sumber protein nabati.', ARRAY['vegetarian','protein']),
('tempe-orek', 'Tempe Orek', 'Lauk', 245, 16, 18, 13, 4, 'Tempe iris goreng dengan kecap manis.', ARRAY['vegetarian']),
('telur-rebus', 'Telur Rebus', 'Protein', 155, 13, 1.1, 11, 0, 'Telur ayam rebus utuh.', ARRAY['protein','sehat']),
('telur-dadar', 'Telur Dadar', 'Protein', 196, 13, 1, 15, 0, 'Telur dadar dengan minyak.', ARRAY['protein']),
('telur-mata-sapi', 'Telur Mata Sapi', 'Protein', 196, 13, 1, 15, 0, 'Telur goreng setengah matang.', ARRAY['protein']),
('ikan-bakar', 'Ikan Bakar', 'Hidangan Utama', 140, 26, 0, 4, 0, 'Ikan dibakar dengan bumbu kecap.', ARRAY['ikan','sehat']),
('ikan-goreng', 'Ikan Goreng', 'Hidangan Utama', 200, 22, 1, 12, 0, 'Ikan goreng bumbu kuning.', ARRAY['ikan']),
('udang-goreng', 'Udang Goreng', 'Hidangan Utama', 180, 24, 2, 9, 0, 'Udang goreng tepung renyah.', ARRAY['seafood']),
('cumi-saus-padang', 'Cumi Saus Padang', 'Hidangan Utama', 145, 16, 8, 6, 0.5, 'Cumi dengan saus padang pedas.', ARRAY['seafood','pedas']),
('bakso', 'Bakso', 'Sup', 120, 10, 8, 6, 0.3, 'Bola daging sapi dalam kuah bening.', ARRAY['sup','populer']),
('mie-ayam', 'Mie Ayam', 'Hidangan Utama', 235, 11, 30, 8, 1.5, 'Mie kuning dengan suwiran ayam manis.', ARRAY['mie','populer']),
('siomay', 'Siomay', 'Cemilan', 175, 9, 15, 9, 1, 'Dumpling ikan kukus dengan bumbu kacang.', ARRAY['kukus']),
('batagor', 'Batagor', 'Cemilan', 240, 10, 22, 13, 1, 'Bakso tahu goreng dengan bumbu kacang.', ARRAY['goreng']),
('pempek', 'Pempek', 'Cemilan', 200, 12, 26, 5, 0.5, 'Kue ikan khas Palembang dengan cuko.', ARRAY['ikan']),
('lontong', 'Lontong', 'Karbohidrat', 144, 2.7, 31, 0.4, 0.5, 'Nasi padat dibungkus daun pisang.', ARRAY['pokok']),
('ketupat', 'Ketupat', 'Karbohidrat', 160, 3, 35, 0.3, 0.5, 'Beras dibungkus janur, dimasak hingga padat.', ARRAY['pokok','lebaran']),
('singkong-rebus', 'Singkong Rebus', 'Karbohidrat', 160, 1.4, 38, 0.3, 1.8, 'Singkong rebus, sumber karbohidrat kompleks.', ARRAY['umbi']),
('ubi-rebus', 'Ubi Rebus', 'Karbohidrat', 86, 1.6, 20, 0.1, 3, 'Ubi jalar rebus, kaya vitamin A.', ARRAY['umbi','sehat']),
('kentang-rebus', 'Kentang Rebus', 'Karbohidrat', 87, 1.9, 20, 0.1, 1.8, 'Kentang rebus tanpa kulit.', ARRAY['umbi']),
('jagung-rebus', 'Jagung Rebus', 'Karbohidrat', 96, 3.4, 21, 1.5, 2.4, 'Jagung manis rebus.', ARRAY['serealia']),
('roti-tawar', 'Roti Tawar', 'Karbohidrat', 265, 9, 49, 3.2, 2.7, 'Roti tawar gandum putih.', ARRAY['roti']),
('roti-gandum', 'Roti Gandum', 'Karbohidrat', 247, 13, 41, 3.4, 7, 'Roti gandum utuh, tinggi serat.', ARRAY['roti','sehat']),
('oatmeal', 'Oatmeal', 'Karbohidrat', 68, 2.4, 12, 1.4, 1.7, 'Bubur oat dengan air.', ARRAY['sehat','sarapan','diet']),
('pisang', 'Pisang', 'Buah', 89, 1.1, 23, 0.3, 2.6, 'Pisang ambon segar.', ARRAY['buah','sehat']),
('apel', 'Apel', 'Buah', 52, 0.3, 14, 0.2, 2.4, 'Apel segar dengan kulit.', ARRAY['buah','sehat']),
('jeruk', 'Jeruk', 'Buah', 47, 0.9, 12, 0.1, 2.4, 'Jeruk manis segar.', ARRAY['buah','vitamin c']),
('mangga', 'Mangga', 'Buah', 60, 0.8, 15, 0.4, 1.6, 'Mangga harum manis.', ARRAY['buah']),
('pepaya', 'Pepaya', 'Buah', 43, 0.5, 11, 0.3, 1.7, 'Pepaya matang, melancarkan pencernaan.', ARRAY['buah','sehat']),
('semangka', 'Semangka', 'Buah', 30, 0.6, 8, 0.2, 0.4, 'Semangka segar tinggi air.', ARRAY['buah']),
('alpukat', 'Alpukat', 'Buah', 160, 2, 9, 15, 7, 'Alpukat, kaya lemak baik.', ARRAY['buah','sehat']),
('nanas', 'Nanas', 'Buah', 50, 0.5, 13, 0.1, 1.4, 'Nanas segar.', ARRAY['buah']),
('anggur', 'Anggur', 'Buah', 69, 0.7, 18, 0.2, 0.9, 'Anggur merah segar.', ARRAY['buah']),
('strawberi', 'Strawberi', 'Buah', 33, 0.7, 8, 0.3, 2, 'Strawberi segar.', ARRAY['buah']),
('durian', 'Durian', 'Buah', 147, 1.5, 27, 5.3, 3.8, 'Durian, raja buah tropis.', ARRAY['buah']),
('rambutan', 'Rambutan', 'Buah', 68, 0.9, 16, 0.2, 0.9, 'Rambutan manis tropis.', ARRAY['buah']),
('salak', 'Salak', 'Buah', 82, 0.4, 21, 0.4, 0.3, 'Salak pondoh manis.', ARRAY['buah']),
('bayam', 'Bayam', 'Sayur', 23, 2.9, 3.6, 0.4, 2.2, 'Bayam hijau, kaya zat besi.', ARRAY['sayur','sehat']),
('kangkung', 'Kangkung', 'Sayur', 19, 2.6, 3.1, 0.2, 2.1, 'Kangkung tumis, sayur populer.', ARRAY['sayur']),
('brokoli', 'Brokoli', 'Sayur', 34, 2.8, 7, 0.4, 2.6, 'Brokoli rebus.', ARRAY['sayur','sehat']),
('wortel', 'Wortel', 'Sayur', 41, 0.9, 10, 0.2, 2.8, 'Wortel mentah, kaya vitamin A.', ARRAY['sayur','sehat']),
('terong', 'Terong', 'Sayur', 25, 1, 6, 0.2, 3, 'Terong ungu rebus.', ARRAY['sayur']),
('timun', 'Timun', 'Sayur', 16, 0.7, 3.6, 0.1, 0.5, 'Timun segar.', ARRAY['sayur']),
('tomat', 'Tomat', 'Sayur', 18, 0.9, 3.9, 0.2, 1.2, 'Tomat segar.', ARRAY['sayur']),
('sawi', 'Sawi Hijau', 'Sayur', 27, 2.9, 4.7, 0.4, 3.2, 'Sawi hijau rebus.', ARRAY['sayur']),
('buncis', 'Buncis', 'Sayur', 31, 1.8, 7, 0.2, 2.7, 'Buncis rebus.', ARRAY['sayur']),
('kacang-panjang', 'Kacang Panjang', 'Sayur', 47, 2.8, 8, 0.4, 3.6, 'Kacang panjang tumis.', ARRAY['sayur']),
('jamur', 'Jamur', 'Sayur', 22, 3.1, 3.3, 0.3, 1, 'Jamur kancing segar.', ARRAY['sayur']),
('tahu-putih', 'Tahu Putih', 'Protein Nabati', 76, 8, 1.9, 4.8, 0.3, 'Tahu putih mentah.', ARRAY['vegetarian']),
('tempe', 'Tempe', 'Protein Nabati', 192, 19, 7.6, 11, 9, 'Tempe segar, fermentasi kedelai.', ARRAY['vegetarian','protein']),
('kacang-merah', 'Kacang Merah', 'Protein Nabati', 127, 9, 23, 0.5, 6.4, 'Kacang merah rebus.', ARRAY['legum']),
('kacang-tanah', 'Kacang Tanah', 'Cemilan', 567, 26, 16, 49, 8.5, 'Kacang tanah panggang.', ARRAY['kacang','protein']),
('kacang-almond', 'Kacang Almond', 'Cemilan', 579, 21, 22, 50, 12, 'Almond mentah.', ARRAY['kacang','sehat']),
('susu-sapi', 'Susu Sapi', 'Minuman', 61, 3.2, 4.8, 3.3, 0, 'Susu sapi murni full cream.', ARRAY['susu']),
('susu-kedelai', 'Susu Kedelai', 'Minuman', 33, 2.8, 1.8, 1.6, 0.6, 'Susu kedelai tanpa gula.', ARRAY['susu nabati']),
('yogurt', 'Yogurt', 'Susu', 59, 10, 3.6, 0.4, 0, 'Yogurt Yunani tanpa lemak.', ARRAY['susu','protein']),
('keju-cheddar', 'Keju Cheddar', 'Susu', 402, 25, 1.3, 33, 0, 'Keju cheddar block.', ARRAY['susu']),
('es-teh-manis', 'Es Teh Manis', 'Minuman', 40, 0, 10, 0, 0, 'Teh dengan gula dan es.', ARRAY['minuman','manis']),
('kopi-hitam', 'Kopi Hitam', 'Minuman', 2, 0.3, 0, 0, 0, 'Kopi hitam tanpa gula.', ARRAY['minuman']),
('kopi-susu', 'Kopi Susu', 'Minuman', 60, 1.5, 9, 2, 0, 'Kopi dengan susu kental manis.', ARRAY['minuman']),
('jus-jeruk', 'Jus Jeruk', 'Minuman', 45, 0.7, 10, 0.2, 0.2, 'Jus jeruk segar tanpa gula.', ARRAY['minuman']),
('air-kelapa', 'Air Kelapa', 'Minuman', 19, 0.7, 3.7, 0.2, 1.1, 'Air kelapa muda alami.', ARRAY['minuman','sehat']),
('soda', 'Soda', 'Minuman', 41, 0, 11, 0, 0, 'Minuman berkarbonasi manis.', ARRAY['minuman']),
('martabak-manis', 'Martabak Manis', 'Cemilan', 350, 7, 50, 14, 1, 'Martabak manis cokelat keju.', ARRAY['cemilan','manis']),
('martabak-telur', 'Martabak Telur', 'Cemilan', 270, 11, 22, 16, 1, 'Martabak telur dengan daging.', ARRAY['cemilan']),
('pisang-goreng', 'Pisang Goreng', 'Cemilan', 230, 1.7, 33, 11, 2, 'Pisang celup tepung goreng.', ARRAY['cemilan','goreng']),
('tahu-isi', 'Tahu Isi', 'Cemilan', 220, 8, 18, 13, 1.5, 'Tahu isi sayur goreng.', ARRAY['cemilan']),
('risoles', 'Risoles', 'Cemilan', 230, 6, 22, 13, 1, 'Kulit risoles isi sayur dan daging.', ARRAY['cemilan']),
('lemper', 'Lemper', 'Cemilan', 195, 4, 30, 6, 0.6, 'Ketan isi abon dibungkus daun.', ARRAY['cemilan']),
('klepon', 'Klepon', 'Cemilan', 180, 2, 40, 3, 0.5, 'Bola ketan isi gula merah balur kelapa.', ARRAY['cemilan','manis']),
('onde-onde', 'Onde-Onde', 'Cemilan', 230, 4, 35, 8, 1.5, 'Bola tepung ketan isi kacang hijau.', ARRAY['cemilan']),
('donat', 'Donat', 'Cemilan', 452, 5, 51, 25, 1.4, 'Donat goreng gula.', ARRAY['cemilan']),
('es-krim', 'Es Krim', 'Cemilan', 207, 3.5, 24, 11, 0.7, 'Es krim vanila standar.', ARRAY['cemilan','manis']),
('cokelat', 'Cokelat', 'Cemilan', 546, 4.9, 61, 31, 7, 'Cokelat batangan susu.', ARRAY['cemilan','manis']),
('kerupuk-udang', 'Kerupuk Udang', 'Cemilan', 532, 6, 64, 30, 0.5, 'Kerupuk udang goreng.', ARRAY['cemilan']),
('emping', 'Emping Melinjo', 'Cemilan', 458, 12, 64, 17, 4, 'Emping melinjo goreng.', ARRAY['cemilan']),
('keripik-kentang', 'Keripik Kentang', 'Cemilan', 536, 7, 53, 35, 4.8, 'Keripik kentang asin.', ARRAY['cemilan']),
('madu', 'Madu', 'Lain', 304, 0.3, 82, 0, 0.2, 'Madu murni alami.', ARRAY['pemanis']),
('gula-pasir', 'Gula Pasir', 'Lain', 387, 0, 100, 0, 0, 'Gula pasir putih.', ARRAY['pemanis']),
('minyak-kelapa', 'Minyak Kelapa', 'Lain', 862, 0, 0, 100, 0, 'Minyak kelapa murni (VCO).', ARRAY['lemak']),
('santan-kental', 'Santan Kental', 'Lain', 230, 2.3, 6, 24, 2.2, 'Santan kelapa kental.', ARRAY['lemak']);
