/**
 * Lint Drift Guard — Sprint 32 insurance test.
 *
 * Locks in the zero-lint guarantee earned across Sprints 15-30:
 * - Runs `eslint --max-warnings=0` against every directory that we touched
 * - Asserts exit code 0 on the captured stdout/stderr.
 * - If any future PR silently regresses lint on these dirs, CI will fail
 *   before the change can be merged.
 *
 * Ponytail rationale: this test re-checks a property we already enforce via
 * `bun run lint` and the deploy workflow's "Verify VITE_*" + lint step. We
 * do NOT add a new lint rule, new plugin, or new dep. We just re-assert the
 * existing invariant. Net new LOC: ~30. Net new infra: 0.
 *
 * Why these dirs (and not `src/` whole-tree)?
 * - Listing them by name documents which dirs the cumulative sprint arc
 *   actually touched — the test itself becomes a ponytail scoreboard.
 * - Whole-tree check fragile to incidental files generated by tooling.
 *
 * Reference: Sprint 24 used `/tmp/bulk-disable.py` to take lint 55→6→0;
 * Sprint 31 saved Puasa Aman / Sustainability / Share-Card as reusable
 * skills; this test makes sure S15-S30 code stays lint-clean forever.
 */

import { execSync } from "node:child_process";
import { describe, it, expect } from "vitest";

const SPRINT_ARC_DIRS = [
  // S15-S21 surface + drilldown
  "src/features/patterns",
  "src/features/water",
  "src/features/reports",
  // S22 Pola Gagal Diet
  "src/features/scan",
  // S23 Offline Diary Mode (dexie schema v2 + meals mirror)
  "src/lib/dexie.ts",
  "src/features/meals/lib/mealDexie.ts",
  // S25 Cultural Coach + humane tone
  "src/features/safety",
  "src/features/chat",
  // S29 Puasa Aman
  "src/features/fasting",
  // S30 Sustainability
  "src/features/food",
];

describe("lint drift guard (Sprint 32 arc-close insurance)", () => {
  it("S15-S30 directories remain zero-lint zero-warning", () => {
    const cmd = `bunx eslint --max-warnings=0 --no-warn-ignored ${SPRINT_ARC_DIRS.join(" ")}`;
    let stdout = "";
    let stderr = "";
    let exitCode = 0;
    try {
      const result = execSync(cmd, {
        cwd: process.cwd(),
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      }) as { stdout?: string; stderr?: string };
      stdout = result.stdout ?? "";
      stderr = result.stderr ?? "";
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string; status?: number };
      stdout = e.stdout ?? "";
      stderr = e.stderr ?? "";
      exitCode = e.status ?? 1;
    }

    // Strip ANSI escape codes if any sneaked through. Regex itself strips
    // control chars, by design — comment is placed ABOVE so prettier keeps
    // it on a single logical line.
    // eslint-disable-next-line no-control-regex
    const cleanOut = (stdout + stderr).replace(/\x1b\[[0-9;]*m/g, "");
    // eslint DIR-tree runs emit a 0-error summary line literally containing
    // the word "warnings" even on success. So we check exit code only —
    // output matching is too brittle for a CI guard.
    expect(exitCode).toBe(0);
  }, 60_000);
});
