/**
 * AUDIT-017 Phase 3 — server-only retention operations.
 *
 * Imported by `persistUserMessage` (on-write check) and by the
 * server function `setChatRetention` (UI toggle). Never imported
 * from client code — the `.server.ts` suffix enforces that.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import { type ChatRetentionDays, validateChatRetentionDays } from "./chatRetention";
import { logServerError } from "@/lib/logger.server";

type SB = SupabaseClient<Database>;
// Local-cast alias: the Supabase `Database` type is auto-generated
// from the live DB schema. The new `chat_retention_days` column +
// `purge_user_chats` RPC are added in migration
// 20260616123743_audit_017_chat_retention.sql but the local type
// snapshot is generated by `supabase gen types` and won't include
// them until the migration is applied + types regenerated.
// We use a loose `any` cast here so this file compiles against
// the pre-migration type snapshot. Runtime is unaffected.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type LooseSB = any;

/**
 * Read the current retention setting for a user. Returns null if
 * the user has no profile row yet (shouldn't happen for authed
 * users, but defensive).
 */
export async function getChatRetention(supabase: SB, userId: string): Promise<ChatRetentionDays> {
  const { data, error } = await (supabase as LooseSB)
    .from("profiles")
    .select("chat_retention_days")
    .eq("id", userId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return (data?.chat_retention_days ?? null) as ChatRetentionDays;
}

/**
 * Update the retention setting. Uses RLS (the existing "own profile
 * update" policy) so users can only set their own retention.
 */
export async function setChatRetention(
  supabase: SB,
  userId: string,
  days: ChatRetentionDays,
): Promise<ChatRetentionDays> {
  const cleaned = validateChatRetentionDays(days);
  const { error } = await (supabase as LooseSB)
    .from("profiles")
    .update({ chat_retention_days: cleaned })
    .eq("id", userId);
  if (error) throw new Error(error.message);
  return cleaned;
}

/**
 * On-write retention check. Called from `persistUserMessage` AFTER
 * the new message is inserted. If the user has a retention period
 * set, this purges their old messages in the same transaction.
 *
 * Errors are swallowed (logged via logServerError so the underlying
 * Supabase row-identifier leak risk is mitigated) so a purge
 * failure never blocks a chat send.
 * send will retry.
 */
export async function enforceRetentionAfterWrite(
  supabase: SB,
  userId: string,
): Promise<{ deleted: number } | null> {
  try {
    const days = await getChatRetention(supabase, userId);
    if (days === null) return null; // forever, nothing to do

    // Use the SQL function via service_role. We need service_role
    // for the RPC call since authenticated can't invoke it (the
    // migration revokes that). Switch to supabaseAdmin via dynamic
    // import to keep this helper server-only.
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data, error } = await (supabaseAdmin as LooseSB).rpc("purge_user_chats", {
      p_user_id: userId,
      p_retention_days: days,
    });
    if (error) throw error;
    return { deleted: Number(data ?? 0) };
  } catch (e) {
    // Best-effort — log but don't fail the chat send.
    logServerError("chat-retention.enforce", e);
    return null;
  }
}
